package org.globsframework.model.generator;

import org.globsframework.core.metamodel.fields.Field;
import org.globsframework.core.model.Glob;
import org.globsframework.core.model.globaccessor.get.GlobGetAccessor;

/**
 * Superclass of the generated get accessors. The subclass generated by {@link AsmAccessorGenerator}
 * implements the typed get() (plus getNative() where it pays) by reading the Glob field directly, and
 * overrides isSet/isNull with a mask read at a constant index.
 * <p>
 * The two below are the fallback used when generation is off (globs.generate.accessors=false) : they go
 * through field.getIndex(), and isNull through a doGet that boxes on the primitive flavour.
 * <p>
 * getValue() is deliberately NOT implemented here : each typed accessor interface provides it as a default
 * that forwards to its own get(), and a concrete method in this class would win over that default.
 */
public abstract class AbstractGeneratedGetAccessor implements GlobGetAccessor {
    protected final Field field;

    protected AbstractGeneratedGetAccessor(Field field) {
        this.field = field;
    }

    public boolean isSet(Glob glob) {
        return glob.isSet(field);
    }

    public boolean isNull(Glob glob) {
        return ((AbstractGlob) glob).doGet(field) == null;
    }
}
