package org.globsframework.model.generator;

import org.globsframework.core.metamodel.GlobType;
import org.globsframework.core.metamodel.fields.Field;
import org.globsframework.core.model.generate.read.GenerateCaller;
import org.globsframework.core.model.generate.read.GeneratedFunctionCaller;
import org.globsframework.core.model.generate.read.GlobGenerateFactory;
import org.globsframework.core.model.globaccessor.get.GlobGetAccessor;
import org.globsframework.core.model.globaccessor.set.GlobSetAccessor;
import org.globsframework.core.utils.exceptions.ItemNotFound;

/**
 * Superclass of every generated GlobFactory.
 * <p>
 * The generated factories used to extend core's DefaultGlobFactory, whose accessors cast the Glob to
 * AbstractDefaultGlob : against a generated Glob that is a ClassCastException.
 * <p>
 * Following the convention of the rest of the framework, the metamodel is walked once in the constructor
 * and the result is a per-field table indexed by Field.getIndex() : no reflection, no lookup per call.
 * The accessors themselves come from the {@link AccessorProvider} the generator passes in, so the table is
 * complete and final when the constructor returns — there is no second phase and no window during which
 * the factory answers with an accessor that is about to be replaced. Subclasses (the generated bytecode)
 * only have to provide create(Object).
 */
public abstract class AbstractGeneratedGlobFactory implements GlobGenerateFactory {
    private final GlobType type;
    private final GlobGetAccessor[] getAccessors;
    private final GlobSetAccessor[] setAccessors;
    private final GenerateCaller callerGenerator;

    protected AbstractGeneratedGlobFactory(GlobType type, AccessorProvider accessors, GenerateCaller callerGenerator) {
        this.type = type;
        this.callerGenerator = callerGenerator;
        Field[] fields = type.getFields();
        getAccessors = new GlobGetAccessor[fields.length];
        setAccessors = new GlobSetAccessor[fields.length];
        for (Field field : fields) {
            getAccessors[field.getIndex()] = accessors.get(field);
            setAccessors[field.getIndex()] = accessors.set(field);
        }
    }

    public GlobType getGlobType() {
        return type;
    }

    /**
     * Generates a caller over the generated Glob class of this type. Comes from the generator rather than
     * being built here, because only the generator holds the ClassLoader that can resolve that class.
     */
    public <D, E> GeneratedFunctionCaller<D, E> create(GenerateCaller.GetFieldValueFunction<D, E> getFieldValueFunction) {
        return callerGenerator.create(getFieldValueFunction);
    }

    public GlobGetAccessor getGetValueAccessor(Field field) {
        return getAccessors[checkedIndex(field)];
    }

    public GlobSetAccessor getSetValueAccessor(Field field) {
        return setAccessors[checkedIndex(field)];
    }

    /**
     * The factory is built from DefaultGlobType's constructor, where the fields do not point back to their
     * GlobType yet : the ownership check has to tolerate a null getGlobType(), and the error message must
     * not call getFullName() which would NPE on it.
     */
    private int checkedIndex(Field field) {
        int index = field.getIndex();
        if (index < 0 || index >= getAccessors.length
            || (field.getGlobType() != null && field.getGlobType() != type)) {
            throw new ItemNotFound(field.getName() + " does not belong to " + type.getName());
        }
        return index;
    }
}
