package org.globsframework.model.generator;

import org.globsframework.core.metamodel.GlobType;
import org.globsframework.core.metamodel.fields.*;
import org.globsframework.core.model.Glob;
import org.globsframework.core.model.GlobFactory;
import org.globsframework.core.model.MutableGlob;
import org.globsframework.core.model.globaccessor.get.*;
import org.globsframework.core.model.globaccessor.set.*;
import org.globsframework.core.utils.exceptions.ItemNotFound;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.ZonedDateTime;

/**
 * Superclass of every generated GlobFactory.
 * <p>
 * The generated factories used to extend core's DefaultGlobFactory, whose accessors cast the Glob to
 * AbstractDefaultGlob : against a generated Glob that is a ClassCastException. Accessors are built here
 * instead, on top of doGet/doSet, which every generated Glob implements through AbstractMutableGlob.
 * <p>
 * Following the convention of the rest of the framework, the metamodel is walked once in the constructor
 * and the result is a per-field table indexed by Field.getIndex() : no reflection, no lookup per call.
 * Subclasses (the generated bytecode) only have to provide create(Object).
 */
public abstract class AbstractGeneratedGlobFactory implements GlobFactory {
    private final GlobType type;
    private final GlobGetAccessor[] getAccessors;
    private final GlobSetAccessor[] setAccessors;

    protected AbstractGeneratedGlobFactory(GlobType type) {
        this.type = type;
        Field[] fields = type.getFields();
        getAccessors = new GlobGetAccessor[fields.length];
        setAccessors = new GlobSetAccessor[fields.length];
        AccessorBuilder builder = new AccessorBuilder();
        for (Field field : fields) {
            field.safeAccept(builder);
            getAccessors[field.getIndex()] = builder.getAccessor;
            setAccessors[field.getIndex()] = builder.setAccessor;
        }
    }

    /**
     * Replaces the doGet/doSet-based accessor of one field with the bytecode-generated one, which reads and
     * writes the Glob field directly. Called by the generators right after the factory is instantiated; the
     * table built by the constructor stays in place as a fallback for any field left uninstalled.
     */
    public void installAccessors(Field field, GlobGetAccessor getAccessor, GlobSetAccessor setAccessor) {
        int index = checkedIndex(field);
        getAccessors[index] = getAccessor;
        setAccessors[index] = setAccessor;
    }

    public GlobType getGlobType() {
        return type;
    }

    public GlobGetAccessor getGetValueAccessor(Field field) {
        return getAccessors[checkedIndex(field)];
    }

    public GlobSetAccessor getSetValueAccessor(Field field) {
        return setAccessors[checkedIndex(field)];
    }

    /**
     * The factory is built from DefaultGlobType's constructor, where the fields do not point back to their
     * GlobType yet : the ownership check has to tolerate a null getGlobType(), and the error message must
     * not call getFullName() which would NPE on it.
     */
    private int checkedIndex(Field field) {
        int index = field.getIndex();
        if (index < 0 || index >= getAccessors.length
            || (field.getGlobType() != null && field.getGlobType() != type)) {
            throw new ItemNotFound(field.getName() + " does not belong to " + type.getName());
        }
        return index;
    }

    private static Object doGet(Glob glob, Field field) {
        return ((AbstractGlob) glob).doGet(field);
    }

    private static void doSet(MutableGlob glob, Field field, Object value) {
        ((AbstractMutableGlob) glob).doSet(field, value);
    }

    /** isSet / isNull are shared by every get accessor : only the typed get() differs. */
    private abstract static class AbstractGet implements GlobGetAccessor {
        final Field field;

        AbstractGet(Field field) {
            this.field = field;
        }

        public boolean isSet(Glob glob) {
            return glob.isSet(field);
        }

        public boolean isNull(Glob glob) {
            return doGet(glob, field) == null;
        }
    }

    private abstract static class AbstractSet {
        final Field field;

        AbstractSet(Field field) {
            this.field = field;
        }
    }

    private static class GetInteger extends AbstractGet implements GlobGetIntAccessor {
        GetInteger(Field field) { super(field); }
        public Integer get(Glob glob) { return (Integer) doGet(glob, field); }
    }

    private static class GetIntegerArray extends AbstractGet implements GlobGetIntArrayAccessor {
        GetIntegerArray(Field field) { super(field); }
        public int[] get(Glob glob) { return (int[]) doGet(glob, field); }
    }

    private static class GetDouble extends AbstractGet implements GlobGetDoubleAccessor {
        GetDouble(Field field) { super(field); }
        public Double get(Glob glob) { return (Double) doGet(glob, field); }
    }

    private static class GetDoubleArray extends AbstractGet implements GlobGetDoubleArrayAccessor {
        GetDoubleArray(Field field) { super(field); }
        public double[] get(Glob glob) { return (double[]) doGet(glob, field); }
    }

    private static class GetLong extends AbstractGet implements GlobGetLongAccessor {
        GetLong(Field field) { super(field); }
        public Long get(Glob glob) { return (Long) doGet(glob, field); }
    }

    private static class GetLongArray extends AbstractGet implements GlobGetLongArrayAccessor {
        GetLongArray(Field field) { super(field); }
        public long[] get(Glob glob) { return (long[]) doGet(glob, field); }
    }

    private static class GetBigDecimal extends AbstractGet implements GlobGetBigDecimalAccessor {
        GetBigDecimal(Field field) { super(field); }
        public BigDecimal get(Glob glob) { return (BigDecimal) doGet(glob, field); }
    }

    private static class GetBigDecimalArray extends AbstractGet implements GlobGetBigDecimalArrayAccessor {
        GetBigDecimalArray(Field field) { super(field); }
        public BigDecimal[] get(Glob glob) { return (BigDecimal[]) doGet(glob, field); }
    }

    private static class GetString extends AbstractGet implements GlobGetStringAccessor {
        GetString(Field field) { super(field); }
        public String get(Glob glob) { return (String) doGet(glob, field); }
    }

    private static class GetStringArray extends AbstractGet implements GlobGetStringArrayAccessor {
        GetStringArray(Field field) { super(field); }
        public String[] get(Glob glob) { return (String[]) doGet(glob, field); }
    }

    private static class GetBoolean extends AbstractGet implements GlobGetBooleanAccessor {
        GetBoolean(Field field) { super(field); }
        public Boolean get(Glob glob) { return (Boolean) doGet(glob, field); }
    }

    private static class GetBooleanArray extends AbstractGet implements GlobGetBooleanArrayAccessor {
        GetBooleanArray(Field field) { super(field); }
        public boolean[] get(Glob glob) { return (boolean[]) doGet(glob, field); }
    }

    private static class GetDate extends AbstractGet implements GlobGetDateAccessor {
        GetDate(Field field) { super(field); }
        public LocalDate get(Glob glob) { return (LocalDate) doGet(glob, field); }
    }

    private static class GetDateTime extends AbstractGet implements GlobGetDateTimeAccessor {
        GetDateTime(Field field) { super(field); }
        public ZonedDateTime get(Glob glob) { return (ZonedDateTime) doGet(glob, field); }
    }

    private static class GetBytes extends AbstractGet implements GlobGetBytesAccessor {
        GetBytes(Field field) { super(field); }
        public byte[] get(Glob glob) { return (byte[]) doGet(glob, field); }
    }

    private static class GetGlob extends AbstractGet implements GlobGetGlobAccessor {
        GetGlob(Field field) { super(field); }
        public Glob get(Glob glob) { return (Glob) doGet(glob, field); }
    }

    private static class GetGlobArray extends AbstractGet implements GlobGetGlobArrayAccessor {
        GetGlobArray(Field field) { super(field); }
        public Glob[] get(Glob glob) { return (Glob[]) doGet(glob, field); }
    }

    private static class SetInteger extends AbstractSet implements GlobSetIntAccessor {
        SetInteger(Field field) { super(field); }
        public void set(MutableGlob glob, Integer value) { doSet(glob, field, value); }
    }

    private static class SetIntegerArray extends AbstractSet implements GlobSetIntArrayAccessor {
        SetIntegerArray(Field field) { super(field); }
        public void set(MutableGlob glob, int[] value) { doSet(glob, field, value); }
    }

    private static class SetDouble extends AbstractSet implements GlobSetDoubleAccessor {
        SetDouble(Field field) { super(field); }
        public void set(MutableGlob glob, Double value) { doSet(glob, field, value); }
    }

    private static class SetDoubleArray extends AbstractSet implements GlobSetDoubleArrayAccessor {
        SetDoubleArray(Field field) { super(field); }
        public void set(MutableGlob glob, double[] value) { doSet(glob, field, value); }
    }

    private static class SetLong extends AbstractSet implements GlobSetLongAccessor {
        SetLong(Field field) { super(field); }
        public void set(MutableGlob glob, Long value) { doSet(glob, field, value); }
    }

    private static class SetLongArray extends AbstractSet implements GlobSetLongArrayAccessor {
        SetLongArray(Field field) { super(field); }
        public void set(MutableGlob glob, long[] value) { doSet(glob, field, value); }
    }

    private static class SetBigDecimal extends AbstractSet implements GlobSetBigDecimalAccessor {
        SetBigDecimal(Field field) { super(field); }
        public void set(MutableGlob glob, BigDecimal value) { doSet(glob, field, value); }
    }

    private static class SetBigDecimalArray extends AbstractSet implements GlobSetBigDecimalArrayAccessor {
        SetBigDecimalArray(Field field) { super(field); }
        public void set(MutableGlob glob, BigDecimal[] value) { doSet(glob, field, value); }
    }

    private static class SetString extends AbstractSet implements GlobSetStringAccessor {
        SetString(Field field) { super(field); }
        public void set(MutableGlob glob, String value) { doSet(glob, field, value); }
    }

    private static class SetStringArray extends AbstractSet implements GlobSetStringArrayAccessor {
        SetStringArray(Field field) { super(field); }
        public void set(MutableGlob glob, String[] value) { doSet(glob, field, value); }
    }

    private static class SetBoolean extends AbstractSet implements GlobSetBooleanAccessor {
        SetBoolean(Field field) { super(field); }
        public void set(MutableGlob glob, Boolean value) { doSet(glob, field, value); }
    }

    private static class SetBooleanArray extends AbstractSet implements GlobSetBooleanArrayAccessor {
        SetBooleanArray(Field field) { super(field); }
        public void set(MutableGlob glob, boolean[] value) { doSet(glob, field, value); }
    }

    private static class SetDate extends AbstractSet implements GlobSetDateAccessor {
        SetDate(Field field) { super(field); }
        public void set(MutableGlob glob, LocalDate value) { doSet(glob, field, value); }
    }

    private static class SetDateTime extends AbstractSet implements GlobSetDateTimeAccessor {
        SetDateTime(Field field) { super(field); }
        public void set(MutableGlob glob, ZonedDateTime value) { doSet(glob, field, value); }
    }

    private static class SetBytes extends AbstractSet implements GlobSetBytesAccessor {
        SetBytes(Field field) { super(field); }
        public void set(MutableGlob glob, byte[] value) { doSet(glob, field, value); }
    }

    private static class SetGlob extends AbstractSet implements GlobSetGlobAccessor {
        SetGlob(Field field) { super(field); }
        public void set(MutableGlob glob, Glob value) { doSet(glob, field, value); }
    }

    private static class SetGlobArray extends AbstractSet implements GlobSetGlobArrayAccessor {
        SetGlobArray(Field field) { super(field); }
        public void set(MutableGlob glob, Glob[] values) { doSet(glob, field, values); }
    }

    /** Union fields carry a Glob (resp. a Glob[]) so they reuse the Glob accessors. */
    private static class AccessorBuilder implements FieldVisitor {
        GlobGetAccessor getAccessor;
        GlobSetAccessor setAccessor;

        public void visitInteger(IntegerField field) {
            getAccessor = new GetInteger(field);
            setAccessor = new SetInteger(field);
        }

        public void visitIntegerArray(IntegerArrayField field) {
            getAccessor = new GetIntegerArray(field);
            setAccessor = new SetIntegerArray(field);
        }

        public void visitDouble(DoubleField field) {
            getAccessor = new GetDouble(field);
            setAccessor = new SetDouble(field);
        }

        public void visitDoubleArray(DoubleArrayField field) {
            getAccessor = new GetDoubleArray(field);
            setAccessor = new SetDoubleArray(field);
        }

        public void visitLong(LongField field) {
            getAccessor = new GetLong(field);
            setAccessor = new SetLong(field);
        }

        public void visitLongArray(LongArrayField field) {
            getAccessor = new GetLongArray(field);
            setAccessor = new SetLongArray(field);
        }

        public void visitBigDecimal(BigDecimalField field) {
            getAccessor = new GetBigDecimal(field);
            setAccessor = new SetBigDecimal(field);
        }

        public void visitBigDecimalArray(BigDecimalArrayField field) {
            getAccessor = new GetBigDecimalArray(field);
            setAccessor = new SetBigDecimalArray(field);
        }

        public void visitString(StringField field) {
            getAccessor = new GetString(field);
            setAccessor = new SetString(field);
        }

        public void visitStringArray(StringArrayField field) {
            getAccessor = new GetStringArray(field);
            setAccessor = new SetStringArray(field);
        }

        public void visitBoolean(BooleanField field) {
            getAccessor = new GetBoolean(field);
            setAccessor = new SetBoolean(field);
        }

        public void visitBooleanArray(BooleanArrayField field) {
            getAccessor = new GetBooleanArray(field);
            setAccessor = new SetBooleanArray(field);
        }

        public void visitDate(DateField field) {
            getAccessor = new GetDate(field);
            setAccessor = new SetDate(field);
        }

        public void visitDateTime(DateTimeField field) {
            getAccessor = new GetDateTime(field);
            setAccessor = new SetDateTime(field);
        }

        public void visitBytes(BytesField field) {
            getAccessor = new GetBytes(field);
            setAccessor = new SetBytes(field);
        }

        public void visitGlob(GlobField field) {
            getAccessor = new GetGlob(field);
            setAccessor = new SetGlob(field);
        }

        public void visitGlobArray(GlobArrayField field) {
            getAccessor = new GetGlobArray(field);
            setAccessor = new SetGlobArray(field);
        }

        public void visitUnionGlob(GlobUnionField field) {
            getAccessor = new GetGlob(field);
            setAccessor = new SetGlob(field);
        }

        public void visitUnionGlobArray(GlobArrayUnionField field) {
            getAccessor = new GetGlobArray(field);
            setAccessor = new SetGlobArray(field);
        }
    }
}
