package org.globsframework.model.generator;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.regex.Pattern;

/**
 * Builds the name of a generated class out of what identifies it, rather than out of a counter.
 * <p>
 * A counter is what the generators used, and it makes a class unrecognisable from one run of the application
 * to the next : the same GlobType is {@code _3} here and {@code _7} there, depending only on the order types
 * happened to be built in. That is enough to make an AOT cache useless for these classes, since it matches a
 * class of a user-defined loader on its name and its bytes.
 * <p>
 * So a name is made of two halves : a readable part, sanitised out of what a human would call this class
 * (the caller's purpose, the type name), and a digest of everything the emitted bytes depend on. The
 * readable part is for stack traces and profiles and nothing else — the digest is what makes the name
 * <em>mean</em> something, and it is why the readable part can be cut to size without becoming a collision :
 * two names that sanitise alike differ in their digest.
 * <p>
 * Hence the short form. A class name is read in stack traces and flame graphs, and — the day these classes
 * are written to disk, which is what a bytes cache or a build-time generation would do — it <em>is</em> a
 * file path, where a component over 255 bytes is a hard limit rather than an annoyance. Each readable part
 * is therefore capped on its own, so that a long purpose cannot eat the type name next to it : a GlobType is
 * usually named after a fully qualified class, and truncating the pair as one string dropped exactly the end
 * that told them apart.
 * <p>
 * <b>The invariant to keep</b> : every argument that changes a single emitted byte has to be in the digest.
 * Two runs can then only produce the same name for byte-identical classes, so a stale cache entry can never
 * be taken for a fresh one — a changed layout, a changed flavour or a changed emitter is a different name,
 * not the same name with different bytes.
 */
public final class GeneratedName {
    /**
     * Bumped by hand whenever the emitted bytecode changes in a way the arguments of a digest do not
     * describe — a fix in a generator, a new emitted method, a different base class. It is what keeps a
     * class generated by an older globs-generate from answering to the name this one builds.
     */
    private static final int FORMAT = 1;

    private static final Pattern NON_WORD = Pattern.compile("[^\\w]");
    /** per part, not for the whole : long enough to recognise, short enough that two parts still fit */
    private static final int MAX_PART = 20;

    // The suffix that keeps two classes that legitimately want the same name apart : the same purpose asked
    // twice for the same shape, which is a codec built twice (two factories in one process, say). The first
    // one gets the bare name, so the common case is the reproducible one and the duplicates are what pays.
    // It is also what makes the key of a generator's PENDING map unique, since that key is the class name.
    // Kept for the life of the process -- one String and a counter per distinct generated class, which is
    // what the generated classes themselves cost anyway.
    private static final Map<String, AtomicInteger> USED = new ConcurrentHashMap<>();

    private GeneratedName() {
    }

    /**
     * @param prefix   the kind of class, e.g. {@code Caller} — the package says the rest
     * @param readable what to make the name readable with — the caller's purpose, the type name
     * @param identity everything the emitted bytes depend on, digested. Must include the readable parts:
     *                 they are lossy once sanitised and cut, and only the digest keeps them apart.
     * @return a unique internal name (slashes), stable across runs unless the same one is asked for twice.
     */
    public static String unique(String prefix, String[] readable, String... identity) {
        return uniqueOf(prefix + "_" + readable(readable) + "_" + digest(identity));
    }

    /**
     * The half of a name that a whole <em>family</em> of classes generated together shares : a Glob, its
     * factory and its two accessors per field are one family, and derive their names from one key
     * ({@code Glob_<key>}, {@code Factory_<key>}, {@code Get_<key>_<index>}, …). Made unique once here
     * rather than four times, so that the four names cannot end up with different suffixes and stop being
     * one family.
     *
     * @param readable what to make the name readable with, each part capped on its own
     * @param identity everything the emitted bytes of the family depend on, digested
     */
    public static String family(String[] readable, String... identity) {
        // its own namespace : a family key has no prefix, so nothing stops it from reading like the tail of
        // a name from unique(), and the two counts must not be the same count
        return uniqueOf("family:" + readable(readable) + "_" + digest(identity)).substring("family:".length());
    }

    private static String uniqueOf(String base) {
        int used = USED.computeIfAbsent(base, k -> new AtomicInteger()).getAndIncrement();
        return used == 0 ? base : base + "_" + used;
    }

    /** Each part sanitised and capped on its own, then joined : neither can crowd the other out. */
    static String readable(String... parts) {
        StringBuilder builder = new StringBuilder();
        for (String part : parts) {
            String cleaned = NON_WORD.matcher(part).replaceAll("_");
            if (cleaned.length() > MAX_PART) {
                cleaned = cleaned.substring(0, MAX_PART);
            }
            builder.append(builder.isEmpty() ? "" : "_").append(cleaned);
        }
        return builder.toString();
    }

    /**
     * What comes after the last dot. A GlobType is usually named after a fully qualified class, whose
     * package repeats over every type of an application and says nothing here — the digest has the whole
     * name, so nothing is lost by showing only the end of it.
     */
    public static String simpleName(String name) {
        return name.substring(name.lastIndexOf('.') + 1);
    }

    /** 12 hex characters — lower case, so that a name comparison may stay case sensitive. */
    static String digest(String... identity) {
        StringBuilder builder = new StringBuilder().append(FORMAT);
        for (String part : identity) {
            // length-prefixed : "ab" + "c" and "a" + "bc" are different identities
            builder.append('|').append(part == null ? -1 : part.length()).append(':').append(part);
        }
        try {
            byte[] hash = MessageDigest.getInstance("SHA-256")
                    .digest(builder.toString().getBytes(StandardCharsets.UTF_8));
            StringBuilder hex = new StringBuilder(12);
            for (int i = 0; i < 6; i++) {
                hex.append(Character.forDigit((hash[i] >> 4) & 0xF, 16))
                        .append(Character.forDigit(hash[i] & 0xF, 16));
            }
            return hex.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 is required of every JVM", e);
        }
    }
}
